### ISSUE TITLE
Feature : Background injection on pages

### ISSUE THREAD

**Issue by ChronicStone** [PejmanNik/puppeteer-report#34]
Hi,

I was wondering if ppt-report somehow allowed to inject a background as image for each page, while having a header & footer.

So for each page, we would have the header  & footer, and a full page background like this : 
![image](https://user-images.githubusercontent.com/55083156/136283698-cc75f247-3273-4863-80cc-a983e4a0c107.png)

Any idea on how to obtain such result ? 

Thanks by advance

**Comment by PejmanNik** [comment]
Hi, due to puppeteer limitation, this lib separately prints header, footer, and content, and it is almost impossible to have the full background for the page. maybe you could split the image into three parts and adjust its header, footer, and content ( I didn't try it)

But I'm working on a new version, and it already supports page background. You can track it here #12
